services:
  vitvqganvae-train-cifar10:
    build:
      context: .
      dockerfile: docker/cifar10.dockerfile
    image: vitvqganvae:cifar10_v0.0.1
    shm_size: '16g'
    volumes:
      - ./.cache:/vitvqganvae/.cache  # Mount local data directory
      - ./outputs:/vitvqganvae/outputs  # Mount local result directory
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  vitvqganvae-train-celeba:
    build:
      context: .
      dockerfile: docker/celeba.dockerfile
    image: vitvqganvae:celeba_v0.0.1
    shm_size: '32g'
    volumes:
      - ./.cache:/vitvqganvae/.cache  # Mount local data directory
      - ./outputs:/vitvqganvae/outputs  # Mount local result directory
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
networks:
  default:
    name: vitvqganvae_network