services:
  vitvqganvae-train-cifar10:
    build:
      context: .
      dockerfile: docker/cifar10_vqvae.dockerfile
    image: vitvqganvae:cifar10_vqvae_v0.0.1
    shm_size: '16g'
    volumes:
      - ./.cache:/vitvqganvae/.cache  # Mount local data directory
      - ./outputs:/vitvqganvae/outputs  # Mount local result directory
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  vitvqganvae-train-cifar10-dev:
    build:
      context: .
      dockerfile: docker/dev/cifar10_vqvae_dev.dockerfile
    image: vitvqganvae:cifar10_vqvae_dev_v0.0.1
    shm_size: '16g'
    volumes:
      - ./.cache:/vitvqganvae/.cache  # Mount local data directory
      - ./outputs:/vitvqganvae/outputs  # Mount local result directory
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  vitvqganvae-train-cifar10-rvq:
    build:
      context: .
      dockerfile: docker/cifar10_vqvae_rvq.dockerfile
    image: vitvqganvae:cifar10_vqvae_rvq_v0.0.1
    shm_size: '16g'
    volumes:
      - ./.cache:/vitvqganvae/.cache  # Mount local data directory
      - ./outputs:/vitvqganvae/outputs  # Mount local result directory
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  vitvqganvae-train-celeba:
    build:
      context: .
      dockerfile: docker/celeba_vqvae.dockerfile
    image: vitvqganvae:celeba_vqvae_v0.0.1
    shm_size: '32g'
    volumes:
      - ./.cache:/vitvqganvae/.cache  # Mount local data directory
      - ./outputs:/vitvqganvae/outputs  # Mount local result directory
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  vitvqganvae-train-celeba-rvq:
    build:
      context: .
      dockerfile: docker/celeba_vqvae_rvq.dockerfile
    image: vitvqganvae:celeba_vqvae_rvq_v0.0.1
    shm_size: '32g'
    volumes:
      - ./.cache:/vitvqganvae/.cache  # Mount local data directory
      - ./outputs:/vitvqganvae/outputs  # Mount local result directory
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
networks:
  default:
    name: vitvqganvae_network