services:
  cifar10-vqvae-mhvq:
    build:
      context: ../../..
      dockerfile: docker/vqvae/img/cifar10/cifar10_vqvae_mhvq.dockerfile
    image: vitvqganvae:cifar10_vqvae_mhvq
    shm_size: '16g'
    volumes:
      - ./.cache:/vitvqganvae/.cache
      - ./outputs:/vitvqganvae/outputs
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  default:
    external: true
    name: vitvqganvae_network
