name: ellipsoid1024_vqvae_mhvq
exp_root_dir: outputs
exp_dir: ""
trial_dir: ""
n_gpus: 1
seed: 42

dataset_name: ellipsoid1024
dataset_source: hf
dataset_img_key: null
dataset_kwargs:
  root: ./.cache/${dataset_name}

model: VQVAE
model_config: VQVAEConfig
model_kwargs:
  dim: 128
  in_channel: 3
  out_channel: 3
  layers: 1
  layer_mults: null
  num_res_blocks: 0
  group: 4
  conv_type: "conv1d"
  enc_act_func: "LeakyReLU"
  dec_act_func: "GLU"
  enc_act_kwargs: {"negative_slope": 0.1}
  dec_act_kwargs: {"dim": 1}
  first_conv_kernel_size: 10
  quantizer: "VectorQuantize"
  codebook_size: 512
  quantizer_kwargs: {
    "codebook_dim": 64,
    "heads": 8,
    "decay" : 0.99,
    "commitment_weight": 0.25,
    "kmeans_init": True,
    "use_cosine_sim": True
  }
  l2_recon_loss: True

trainer: PCVQVAETrainer
trainer_config: PCVQVAETrainerConfig
trainer_kwargs:
  num_train_steps: 15000
  batch_size: 128
  num_workers: 16
  pin_memory: True
  grad_accum_every: 1
  learning_rate: 1e-4
  weight_decay: 0.
  max_grad_norm: null
  val_every: 500
  val_num_batches: 20
  val_num_images: 32
  scheduler: CosineAnnealingLR
  scheduler_kwargs:
    T_max: "${sub: ${trainer_kwargs.num_train_steps}, ${trainer_kwargs.warmup_steps}}"
    eta_min: 1e-5
  ema_kwargs: null
  accelerator_kwargs: {}
  optimizer_name: Adam
  optimizer_kwargs: {}
  loss_lambda:
    recon_loss: 1.
    quantizer_loss: 1.
  checkpoint_every: 500
  warmup_steps: 0
  use_wandb_tracking: False
  resume: False
  from_checkpoint: null
  from_checkpoint_type: null

wandb:
  project_name: "vitvqganvae"
  run_name: null
  kwargs:
    entity: "heartbeats"