name: cifar10_vqvae_lfq
exp_root_dir: outputs
exp_dir: ""
trial_dir: ""
n_gpus: 1
seed: 42

dataset_name: cifar10
dataset_source: torchvision
dataset_img_key: null
dataset_kwargs:
  root: ./.cache/${dataset_name}
  download: True

model: VQVAE
model_config: VQVAEConfig
model_kwargs:
  dim: 64
  in_channel: 3
  out_channel: 3
  layers: 1
  layer_mults: null
  num_res_blocks: 1
  group: 4
  conv_type: "conv2d"
  enc_act_func: "LeakyReLU"
  dec_act_func: "GLU"
  enc_act_kwargs: {"negative_slope": 0.1}
  dec_act_kwargs: {"dim": 1}
  first_conv_kernel_size: 5
  quantizer: "LFQ"
  codebook_size: 1024
  quantizer_kwargs: {
      "diversity_gamma": 4.,
      "entropy_loss_weight": 0.1
  }
  l2_recon_loss: True

trainer: VQVAETrainer
trainer_config: VQVAETrainerConfig
trainer_kwargs:
  num_train_steps: 15000
  batch_size: 512
  num_workers: 16
  pin_memory: True
  grad_accum_every: 1
  learning_rate: 1e-2
  weight_decay: 0.
  max_grad_norm: null
  val_every: 500
  val_num_batches: 20
  val_num_images: 32
  scheduler: CosineAnnealingLR
  scheduler_kwargs:
    T_max: "${sub: ${trainer_kwargs.num_train_steps}, ${trainer_kwargs.warmup_steps}}"
    eta_min: 5e-05
  ema_kwargs: {}
  accelerator_kwargs: {}
  optimizer_name: Adam
  optimizer_kwargs: {}
  loss_lambda:
    recon_loss: 1.
    quantizer_loss: 1.
  checkpoint_every: 500
  save_results_every: 500
  warmup_steps: 0
  use_wandb_tracking: False
  resume: False
  from_checkpoint: null
  from_checkpoint_type: null

wandb:
  project_name: "vitvqganvae"
  run_name: null
  kwargs:
    entity: "heartbeats"